### ISSUE TITLE
Hammers don't generate XP 

### ISSUE THREAD

**Issue by ritchieterr** [EwyBoy/Hammer-Time#10]
MC: 1.12.2
Mod Ver: Hammer Time-2.0.2-1.12.2

When I'm minning coal, redstone, lapislazuli or diamond, don't get the XP. It's just me or is a bug?

**Comment by EwyBoy** [comment]
Did not even know that ore dropped XP, but I can fix it^^

**Comment by EwyBoy** [comment]
Did not even know that ore dropped XP, but I can fix it^^

**Comment by EwyBoy** [comment]
Should be fixed now, pushing a build to CurseForge now with the changes.

**Comment by ritchieterr** [comment]
Thank you my friend! Nice job!

*Ricardo J. Terrazas Rivadeneyra*

*Unidad de Vinculación para la Transparencia y Acceso a la Información
Publica *
*Cel. 9831313023*

2018-02-08 15:32 GMT-05:00 EwyBoy <notifications@github.com>:
