### ISSUE TITLE
sickle not in the available

### ISSUE THREAD

**Issue by jonathanpicard** [EwyBoy/Hammer-Time#11]
Hi!

The sickle is not in the jar file, so uncraftable.

Not sure if it's intentional or not.

**Comment by EwyBoy** [comment]
I am not done modeling it for 1.12 yet. The 1.12 version is port rewritten from scratch of the 1.7 version. The model system in Minecraft has changed, and I need some time to remodel and code the sickle. No ETA.

**Comment by jonathanpicard** [comment]
Thanks for the follow up!

We got the file _Hammer Time-2.1.0-1.12.2.jar_ when it was 2 hour old, so we thought it might have been an oversight.

Please take the time you need, we're just happily using your mod in the meantime. 😄

**Comment by EwyBoy** [comment]
Sickle is available in build 2.2.0
