### ISSUE TITLE
bad reference for stone and wood versions

### ISSUE THREAD

**Issue by jonathanpicard** [EwyBoy/Hammer-Time#12]
Hi!

The recipe pictures show the stone and wood versions to be made of cobblestone and wood planks, but they actually use the smooth stone and logs in the jar file.

The reference should be this:

- minecraft:cobblestone
- minecraft:planks

**Comment by EwyBoy** [comment]
Those pictures are old, and I have not had the time to update em, use JEI to check recipes.

**Comment by jonathanpicard** [comment]
Thanks for the confirmation! We were not sure if it was a mistake or not, so I thought to notify you just in case.

(By the way, thank you for making this mod!)

**Comment by EwyBoy** [comment]
^^
