### ISSUE TITLE
1.14.x Adf.ly link invalid

### ISSUE THREAD

**Issue by XARXU** [EwyBoy/Hammer-Time#19]
http://minecraftmodpacks.net/mods/hammer-time/

You have a link to "1.14.x" that makes us disable our AdBlocker, gets you traffic-based revenue, and goes to....nothing. "No files". Wouldn't a legit link have served just as well to bring us to a dead end?

I definitely wouldn't mind hyping your project, but these ad services are sketchy and pimp themselves out to shady websites. I don't feel okay disabling my AdBlocker (which basically helps protect me from viruses these sites transmit), especially for a dead-end link.

It would also be ethical of mod developers to not put a Mod version up you don't have any content out for yet. If you don't have "1.14.4", I'd appreciate you not listing it in your post titles.

**Comment by EwyBoy** [comment]
I don't host any of my mods on that malware infested website you just linked me to.

100% of all official Minecraft mods for Forge is found here on CurseForge: https://www.curseforge.com/minecraft/mc-mods
NO other websites.

Link to the mod is: https://www.curseforge.com/minecraft/mc-mods/hammer-time
Don't use ANY other website when looking for mods.

**Comment by XARXU** [comment]
Good to know. Is there anything you would like us to do about those sites
getting Adf.ly revenue (and infecting computers) on the premise of linking
to your mods and services?

**Comment by EwyBoy** [comment]
It is not really any way to stop these websites but to spread awareness of where to safely download mods from to support their creators. We as the entirety of the modding community have tried to shut these websites down with no luck. Best thing is to maybe report their adf.ly links and teach people to link to CurseForge instead of these sites.
