### ISSUE TITLE
Hammer Breaks Bedrock

### ISSUE THREAD

**Issue by Dragnier** [EwyBoy/Hammer-Time#3]
I was mining and used a diamond hammer to break a block right above bedrock which caused the 3x3 size to actually break the bedrock. This really needs to be fixed. Didn't try any other hammer types, but it may be all of them.

**Comment by EwyBoy** [comment]
Thanks! Gonna look into this.

**Comment by EwyBoy** [comment]
It is fixed now in build https://minecraft.curseforge.com/projects/hammer-time/files/2509579
