### ISSUE TITLE
Recipe

### ISSUE THREAD

**Issue by Goddessa39** [EwyBoy/Hammer-Time#5]
The [wooden] recipe for the hammer is the same as the sign, and nothing shows up with the cobblestone version, etcetera. Was also dissapointed none of the other tools were in the mod, though I understand vacation.

**Comment by EwyBoy** [comment]
Working on the other tools now.
As far as I know signs are not using this recipe and the stone hammer is working fine to.
https://imgur.com/a/m9ArN
If you looked at the recipes from the Curse Forge page, they are outdated. I am gonna redo the site as soon as I get the mod back to how it was back in 1.7.10.

**Comment by Goddessa39** [comment]
six wood planks with a stick at the bottom is the crafting recipe for signs.

**Comment by EwyBoy** [comment]
![image](https://user-images.githubusercontent.com/5883716/34915929-5a874788-f92f-11e7-8547-51298cbd1f7e.png)
It is NOT using planks, also it is two sticks.
