### ISSUE TITLE
No excavators, lumbers. Only Hammers.

### ISSUE THREAD

**Issue by zyudimosha** [EwyBoy/Hammer-Time#7]
Game Version - 1.12.2
Forge Version - 14.23.1.2604
Mod Version - 2.0.2-1.12.2
Library version - bibliotheca-1.2.1-1.12.2

Using JEI or console commands or crafting table i can get only Hammers. Other stuff like lumbers and excavators are not available. So it should be?

**Comment by zyudimosha** [comment]
Oh, Im sorry, found another issue with same problem. Need time to port this stuff.

**Comment by EwyBoy** [comment]
Other tools available now https://minecraft.curseforge.com/projects/hammer-time/files/2530046
Plus many other fixes
